###
# This is the place to override the opsworks_nodejs cookbook's default attributes.
#
# Do not edit THIS file directly. Instead, create
# "opsworks_nodejs/attributes/customize.rb" in your cookbook repository and
# put the overrides in YOUR customize.rb file.
###

# The following shows how to override the Nodejs version:
#
#normal[:opsworks_nodejs][:version] = '0.12.7'
#default[:opsworks_commons][:assets_url] = 'https://opsworks-instance-assets-us-east-1.s3.amazonaws.com'